config/routes.rb
Rails.application.routes.draw do
  resources :searches

  root 'searches#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
require 'nokogiri'
require 'open-uri'

class SearchesController < ApplicationController
  def index

  end

  def create
  	url = "http://www.walmart.com/search/?query=" + params[:search]
  	@searchDisplay = Nokogiri::HTML(open(url))
  	@wordArray = []

  	@searchDisplay.css(".js-product-title").each_with_index do |item, index| 
   		@wordArray << { href: item['href'], title: item.text, image: item.xpath('img') }
   		# .text.gsub(/\s+/, " ")
		end

		@wordArray
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyscrape</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
<%= yield %>
	</div>

</body>
</html>

app/views/searches/create.html.erb
<% @wordArray.each_with_index do |item, index| %>
	<div class="row">
	<%= link_to item[:title], ("http://walmart.com" + item[:href]) %>
	<%= item[:image] %>

	</div>
<% end %>

app/views/searches/index.html.erb
<div class="row">
	<div class="col-md-6">
		<%= form_tag searches_path, :method => 'post' do %>
			<div class="input-group">
		    <%= text_field_tag :search, params[:search], :class => 'form-control' %>
		    <span class="input-group-btn">
		    	<%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
		    </span>
		  </div>
		<% end %>
	</div>
</div>